trigger:
- main   # Trigger on push to main branch

pool:
  name: Default   # Self-hosted agent pool

steps:
- checkout: self

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/myfile.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Skip publishing artifact if you don't need it
# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: 'drop'

# Copy file using scp
- script: |
    echo "Copying $(Build.ArtifactStagingDirectory)/myfile.txt to $vmUser@$vmHost:/home/$vmUser/"
    scp -o StrictHostKeyChecking=no "$(Build.ArtifactStagingDirectory)/myfile.txt" $vmUser@$vmHost:/home/$vmUser/
  displayName: 'Copy file to VM'
  env:
    vmUser: $(vmUser)
    vmHost: $(vmHost)
