trigger:
- master   # Trigger on push to master branch

pool:
  name: Default   # Self-hosted agent pool

steps:
- checkout: self

# Debug: list the source directory
- script: |
    echo "Listing files in Build.SourcesDirectory: $(Build.SourcesDirectory)"
    ls -R $(Build.SourcesDirectory)
  displayName: 'Debug: List source files'

# Copy file directly from source directory to VM
- bash: |
    echo "Copying $(Build.SourcesDirectory)/myfile.txt to ${VM_USER}@${VM_HOST}:/home/${VM_USER}/"
    scp -o StrictHostKeyChecking=no "$(Build.SourcesDirectory)/myfile.txt" "${VM_USER}@${VM_HOST}:/home/${VM_USER}/"
  displayName: 'Copy file to VM'
  env:
    VM_USER: azureuser
    VM_HOST: 20.197.6.131
