trigger:
- master   # Trigger on push to main branch

pool:
  name: Default   # Self-hosted agent pool

steps:
- checkout: self

# Debug: list the source directory
- script: |
    echo "Listing files in Build.SourcesDirectory: $(Build.SourcesDirectory)"
    ls -R $(Build.SourcesDirectory)
  displayName: 'Debug: List source files'

# Copy file directly from source directory to VM
- script: |
    echo "Copying $(Build.SourcesDirectory)/myfile.txt to $vmUser@$vmHost:/home/$vmUser/"
    scp -o StrictHostKeyChecking=no "$(Build.SourcesDirectory)/myfile.txt" $vmUser@$vmHost:/home/$vmUser/
  displayName: 'Copy file to VM'
  env:
    vmUser: $(vmUser)
    vmHost: $(vmHost)
